Repository andela/ah-frontend-odin, pull requests merged in 2018-12, with the labels that each got.

#11 #161340140 Enable social login using facebook & google
  .env
  package.json
  src/components/authentication/FaceBookButton.jsx
  src/components/authentication/GoogleButton.jsx
  src/components/authentication/LoginForm.jsx
  src/components/authentication/LoginModal.jsx
  src/components/authentication/SocialButtons.js
  src/components/icons/Facebook.jsx
  src/components/icons/Google.jsx
  src/containers/App.js
  src/containers/authentication/AuthenticationModals.js
  src/containers/authentication/AuthenticationModals.test.js
  src/forms/index.jsx
  src/sass/_bootstrap_overides.scss
  src/sass/_custom.scss
  src/store/actions/authentication.js
  src/store/actions/authentication.test.js
  src/store/reducers/authentication.js
  src/store/types/articles.js
  src/tests/unit/actions/articles.test.js
  src/tests/unit/components/SocialButtons.test.js
  src/tests/unit/components/__snapshots__/SocialButtons.test.js.snap
  yarn.lock
Labels: Finished

#16 #161340147 Article Tags should be available and linkable.
  src/components/TagList.jsx
Labels: Finished

#23 #161340144 Add articles comments
  .env
  .eslintrc.json
  src/components/articles/ArticleWithDetails.jsx
  src/components/articles/ArticleWithDetails.test.jsx
  src/components/articles/comments/Comment.jsx
  src/components/articles/comments/CommentForm.jsx
  src/components/articles/comments/CommentForm.test.jsx
  src/components/articles/comments/Comments.jsx
  src/components/articles/comments/NewComment.jsx
  src/components/articles/comments/NewComment.test.js
  src/containers/pages/ShowArticle.jsx
  src/containers/pages/ShowArticle.test.js
  src/containers/pages/UnAuthorized.test.js
  src/forms/FormComponent.jsx
  src/forms/index.jsx
  src/sass/_animations.scss
  src/sass/_bootstrap_overides.scss
  src/sass/_variables.scss
  src/store/actions/articles.js
  src/store/actions/articles.test.js
  src/store/actions/authentication.js
  src/store/helpers/index.js
  src/store/index.js
  src/store/reducers/article.js
  src/store/reducers/articles.test.js
  src/store/types/articles.js
  src/tests/factory/article.js
  src/tests/factory/comment.js
  src/utils/Http.js
  src/utils/Http.test.js
  src/utils/articles.js
Labels: Finished

#22 #162689173 Make signup validation errors more descriptive
  package.json
  src/components/authentication/SignupForm.jsx
  src/components/authentication/SignupForm.test.js
  src/components/authentication/SignupModal.jsx
  src/containers/authentication/AuthenticationModals.js
  src/store/actions/articles.js
  src/store/actions/authentication.js
  src/store/actions/authentication.test.js
  src/store/helpers/index.js
  src/store/index.js
  src/store/reducers/authentication.js
  src/store/types/authentication.js
  src/utils/Http.js
  src/utils/notifications.js
Labels: Finished

#26 #161340152 Add Search Functionality and Custom filtering based on parameters (UI)
  src/components/articles/filters/Filters.jsx
  src/components/articles/filters/Filters.test.js
  src/components/articles/filters/index.jsx
  src/components/articles/filters/index.test.js
  src/components/icons/IconSearch.jsx
  src/components/icons/IconSearch.test.js
  src/components/icons/__snapshots__/IconSearch.test.js.snap
  src/containers/App.js
  src/containers/layout/NavBar.js
  src/containers/layout/NavBar.test.js
  src/containers/layout/UILoader.test.jsx
  src/containers/pages/SearchComponent.jsx
  src/containers/pages/SearchComponent.test.js
  src/containers/pages/__snapshots__/HomePage.test.js.snap
  src/containers/pages/__snapshots__/PageNotFound.test.js.snap
  src/sass/_custom.scss
  src/store/actions/filters.js
  src/store/actions/filters.test.js
  src/store/reducers/filters.js
  src/store/reducers/filters.test.js
  src/store/reducers/index.js
  src/store/types/filters.js
  src/utils/articles.js
  src/utils/articles.test.js
Labels: Finished

#24 #161340154 Enable users to bookmark articles for reading later
  src/components/articles/ArticleFooter.jsx
  src/components/articles/ArticleWithDetails.jsx
  src/components/articles/Bookmark.jsx
  src/components/articles/Bookmark.test.js
  src/components/icons/Bookmark.jsx
  src/containers/App.js
  src/containers/pages/ShowArticle.jsx
  src/sass/_custom.scss
  src/store/actions/Bookmark.js
  src/store/actions/bookmark.test.js
  src/store/reducers/Bookmark.js
  src/store/reducers/Bookmark.test.js
  src/store/reducers/index.js
  src/store/types/articles.js
Labels: Finished, code climate issues

#18 #161340141 Enable Users to View and Edit their Profiles
  .env
  package.json
  public/index.html
  src/components/articles/ArticleFooter.jsx
  src/components/authentication/AuthLinks.jsx
  src/components/authentication/AuthLinks.test.js
  src/components/authentication/__snapshots__/AuthLinks.test.js.snap
  src/components/profile/getProfile.jsx
  src/components/profile/getProfile.test.js
  src/components/utils/constants.js
  src/containers/App.js
  src/containers/profiles/profilesContainer.js
  src/containers/profiles/profilesContainer.test.js
  src/sass/_custom.scss
  src/store/actions/articles.js
  src/store/actions/profiles/profileActions.js
  src/store/actions/profiles/profileActions.test.js
  src/store/reducers/index.js
  src/store/reducers/profilesReducer/index.js
  src/store/reducers/profilesReducer/profileReducer.test.js
  src/store/types/profiles.js
  yarn.lock
Labels: Writing tests, in progress

#25 #161340148 Users are able to share articles via social media.
  package.json
  src/components/articles/ArticleWithDetails.jsx
  src/sass/_custom.scss
  yarn.lock
Labels: Finished

#15 #161340138 Users should be able to reset their password
  src/components/authentication/CompletePasswordResetForm.jsx
  src/components/authentication/CompletePasswordResetForm.test.js
  src/components/authentication/LoginForm.jsx
  src/components/authentication/LoginModal.jsx
  src/components/authentication/PasswordResetForm.jsx
  src/components/authentication/PasswordResetForm.test.js
  src/components/authentication/PasswordResetModal.jsx
  src/components/authentication/PasswordResetModal.test.js
  src/containers/App.js
  src/containers/authentication/AuthenticationModals.js
  src/containers/authentication/CompleteReset.jsx
  src/containers/authentication/CompleteReset.test.js
  src/forms/FormComponent.jsx
  src/store/actions/authentication.js
  src/store/actions/authentication.test.js
  src/store/actions/bookmark.test.js
  src/store/reducers/authentication.js
Labels: in progress

#19 #161340143 Users should be able to rate articles
  package.json
  src/components/articles/Article.jsx
  src/components/articles/Article.test.js
  src/components/articles/ArticleRateComponent.jsx
  src/components/articles/ArticleWithDetails.jsx
  src/containers/ArticleRate.jsx
  src/containers/RateArticle.jsx
  src/containers/UnRatedArticle.jsx
  src/sass/_custom.scss
  src/store/actions/articles.js
  src/store/actions/articles.test.js
  src/store/actions/authentication.test.js
  src/store/reducers/article.js
  src/store/reducers/articles.test.js
  src/store/types/articles.js
  src/tests/unit/containers/RateArticlesFunctions.test.js
  src/tests/unit/reducers/RateArticleReducer.test.js
  yarn.lock
Labels: in progress
